- name: Login to Aliyun
        run: docker login -u "${{ secrets.TCR_USER }}" -p "${{ secrets.TCR_PWD }}" crpi-igap1jgyarbenyfr.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Pull, Tag and Push
        run: |
          docker pull ghcr.io/lovedevpanda/rhex:latest
          docker tag ghcr.io/lovedevpanda/rhex:latest crpi-igap1jgyarbenyfr.cn-hangzhou.personal.cr.aliyuncs.com/my-rhex-space/rhex:latest
          docker push crpi-igap1jgyarbenyfr.cn-hangzhou.personal.cr.aliyuncs.com/my-rhex-space/rhex:latest
